// Configuration file for EEA Elasticsearch River Plugin
// check
// https://github.com/eea/eea.elasticsearch.river.rdf/blob/master/README.rst
// to see how the configration options work
// Please do not edit this file directly on production servers

// RDF endpoint to query

var endpoint = 'http://semantic.eea.europa.eu/sparql';
var queryType = 'construct';
var query = ["CONSTRUCT {?s ?p ?o} FROM <http://semantic.eea.europa.eu/project/pam/pam2014.csv> WHERE { ?s ?p ?o}"];

module.exports = {
    'endpoint': endpoint,
    'queryType': queryType,
    'query': query
};
