PREFIX tableFile: <http://semantic.eea.europa.eu/home/szabozo0/pam2015dummy.csv#>
SELECT
 
(concat(
"http://cdr.eionet.europa.eu/Converters/run_conversion?file=",
fn:substring-before(fn:substring-after(?ReportID,"cdr.eionet.europa.eu/"),"#"),
"&conv=524&source=remote#pam",
?_id) as ?details_ext_url)
?_id
?Country
?Name_of_PaM
?Single_or_group_of_PAMs
?Type_of_policy_instrument
?Status_of_implementation
?Policy_impacting_EU_ETS_or_ESD
?Sectors_affected
?GHG_emissions_reductions_2020_total_ktCO2
?GHG_emissions_reductions_2030_total_kt_CO2
?ReportID
?PaM_ID
?Objectives
?Type_of_responsible_Entity
?Implementation_start_year
?Related_Union_policy
?GHG_affected
?Projection_scenario_in_which_PaM_is_included
FROM <http://semantic.eea.europa.eu/home/szabozo0/pam2015dummy.csv>
WHERE {
_:rec tableFile:PaM_ID ?_id .
_:rec tableFile:Country ?Country .
_:rec tableFile:Name_of_PaM ?Name_of_PaM .
_:rec tableFile:Single_or_group_of_PAMs ?Single_or_group_of_PAMs .
_:rec tableFile:Type_of_policy_instrument ?Type_of_policy_instrument .
_:rec tableFile:Status_of_implementation ?Status_of_implementation .
_:rec tableFile:Policy_impacting_EU_ETS_or_ESD ?Policy_impacting_EU_ETS_or_ESD .
_:rec tableFile:Sectors_affected ?Sectors_affected .
_:rec tableFile:GHG_emissions_reductions_2020_total_ktCO2 ?GHG_emissions_reductions_2020_total_ktCO2 .
_:rec tableFile:GHG_emissions_reductions_2030_total_kt_CO2 ?GHG_emissions_reductions_2030_total_kt_CO2 .
_:rec tableFile:ReportID ?ReportID .
_:rec tableFile:PaM_ID ?PaM_ID .
_:rec tableFile:Objectives ?Objectives .
_:rec tableFile:Type_of_responsible_Entity ?Type_of_responsible_Entity .
_:rec tableFile:Implementation_start_year ?Implementation_start_year .
_:rec tableFile:Related_Union_policy ?Related_Union_policy .
_:rec tableFile:GHG_afected ?GHG_affected .
_:rec tableFile:Projection_scenario_in_which_PaM_is_included ?Projection_scenario_in_which_PaM_is_included .
}