PREFIX tableFile: <http://semantic.eea.europa.eu/home/szabozo0/PAM_viewer_Flat_Table_180915.csv#>
SELECT
?Link_to_national_report
?_id
?Country
?Name_of_policy_or_measure
?Single_policy_or_measure__or_group_of_measures
?Type_of_policy_instrument
?Status_of_implementation
?Policy_or_measure_impacting_emissions_under_the_EU_ETS__emissions_trading___the_ESD__outside_the_ETS__or_LULUCF__land_use__land_use_change_and_forestry_
?Sector_s__affected
?Total_GHG_emissions_reductions_in_2020__kt_CO2_equivalent_per_year_
?Total_GHG_emissions_reductions_in_2030__kt_CO2_equivalent_per_year_
?Link_to_national_report
?PAM_number
?Objective
?Entities_responsible_for_implementing_the_policy
?Implementation_period_start
?Is_the_policy_or_measure_related_to_a_Union_policy_
?GHG_s__affected
?Projection_scenario_in_which_the_policy_or_measure_is_included

FROM <http://semantic.eea.europa.eu/home/szabozo0/PAM_viewer_Flat_Table_180915.csv>
WHERE {
_:rec tableFile:PAM_number ?_id .
_:rec tableFile:Country ?Country .
_:rec tableFile:Name_of_policy_or_measure ?Name_of_policy_or_measure .
_:rec tableFile:Single_policy_or_measure__or_group_of_measures ?Single_policy_or_measure__or_group_of_measures .
_:rec tableFile:Type_of_policy_instrument ?Type_of_policy_instrument .
_:rec tableFile:Status_of_implementation ?Status_of_implementation .
_:rec tableFile:Policy_or_measure_impacting_emissions_under_the_EU_ETS__emissions_trading___the_ESD__outside_the_ETS__or_LULUCF__land_use__land_use_change_and_forestry_  ?Policy_or_measure_impacting_emissions_under_the_EU_ETS__emissions_trading___the_ESD__outside_the_ETS__or_LULUCF__land_use__land_use_change_and_forestry_  .
_:rec tableFile:Sector_s__affected ?Sector_s__affected .
_:rec tableFile:Total_GHG_emissions_reductions_in_2020__kt_CO2_equivalent_per_year_ ?Total_GHG_emissions_reductions_in_2020__kt_CO2_equivalent_per_year_ .
_:rec tableFile:Total_GHG_emissions_reductions_in_2030__kt_CO2_equivalent_per_year_ ?Total_GHG_emissions_reductions_in_2030__kt_CO2_equivalent_per_year_ .
_:rec tableFile:Link_to_national_report ?Link_to_national_report .
_:rec tableFile:PAM_number ?PAM_number .
_:rec tableFile:Objective ?Objective .
_:rec tableFile:Entities_responsible_for_implementing_the_policy ?Entities_responsible_for_implementing_the_policy .
_:rec tableFile:Implementation_period_start ?Implementation_period_start .
_:rec tableFile:Is_the_policy_or_measure_related_to_a_Union_policy_ ?Is_the_policy_or_measure_related_to_a_Union_policy_ .
_:rec tableFile:GHG_s__affected ?GHG_s__affected .
_:rec tableFile:Projection_scenario_in_which_the_policy_or_measure_is_included ?Projection_scenario_in_which_the_policy_or_measure_is_included .
}
